version: "3.3"
networks:
  loki:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluentbit
    ports:
        - "24224:24224"
        - "24224:24224/udp"
    volumes:
      - .docker/logging/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - loki
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - loki